NewsPaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('news/', include('news.urls')),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    # path('pages/', include('django.contrib.flatpages.urls')),
    
]
    # path('about/', include('news.url')),
    # мы пишем в адресной строки about и будем брать содержимое в этом месте

NewsPaper/news/urls.py
from django.urls import path
from .views import *
from django.views.decorators.cache import cache_page

app_name = 'news'

urlpatterns = [
    path('news/search/', PostList.as_view(), name='posts'),
    path('', cache_page(60)(CensoredList.as_view())),
    path('news/<int:pk>/', PostDetail.as_view(), name='post'),    
    path('news/', CensoredList.as_view()),
    path('news/add/', PostCreateView.as_view(), name='post_create'), 
    path('news/<int:pk>/edit', PostUpdateView.as_view(), name='post_update'),
    path('news/<int:pk>/card', PostCard.as_view(), name='post_card'),
    path('news/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'), 
    path('user/', IndexView.as_view(), name='user'),
    path('upgra te/', upgrade_me, name='upgrate'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', RegisterView.as_view(), name='signup'),
    path('subscribers/', SubscribersView.as_view(), name='subscribers'),
    


    # path('filter/all/', PostAllView.as_view()),
    # path('news/demo/', News.as_view()),
    # path('news1/', post),
    # path('news', views.index),
]
#     path('about', views.about),

# создали функцию индекс котораяотображает сообщение 

NewsPaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.cache import cache
from django import forms

class BaseRegisterForm(UserCreationForm):
    email = forms.EmailField(label = "Email")
    first_name = forms.CharField(label = "Имя") # опционально, можно не указывать
    last_name = forms.CharField(label = "Фамилия") # опционально

    class Meta:
        model = User
        fields = ("username", 
                  "first_name", # опционально
                  "last_name", # опционально
                  "email", 
                  "password1", 
                  "password2", )
        
class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

class Author(models.Model):
    autorUser = models.OneToOneField(User, on_delete=models.CASCADE) #для связи автора с юзером
    ratingAuthor = models.SmallIntegerField(default=0)

    def apdate_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0

        if postRat.get('postRating') is not None:
            pRat += postRat.get('postRating')

        commentRat = self.autorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0

        if commentRat.get('commentRating') is not None:
            cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()




class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    ARTICLE = 'AR'
    NEWS = 'NW'
    CATEGORY_CHOICES = [
        (ARTICLE, 'Статья'),
        (NEWS, 'Новость'),
    ]
    categoryType = models.CharField(max_length = 2,  choices = CATEGORY_CHOICES, default=ARTICLE)
    dataCreation = models.DateTimeField(auto_now_add = True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    titel = models.CharField(max_length = 128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0) 

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'
    
    def get_absolute_url(self):
        return reverse('news:post', args=[str(self.pk)])
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs) # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его

    
    
class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    

class Mailing(models.Model):
    subscribers = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dataCreation = models.DateTimeField(auto_now_add = True)
    rating = models.SmallIntegerField(default=0) 

    def __str__(self):
        try:
            return self.commentPost.author.autorUser.username
        except:
            return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

NewsPaper/news/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.views import View
from django_filters import FilterSet
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .forms import RegisterForm
from .filters import PostFilter 
from django.shortcuts import redirect 
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from django.core.cache import cache


from .models import *
from .forms import *

# Отправляем форму о том что он успешно подписался на категорию
class SubscribersView(CreateView):
    model = Mailing
    template_name = 'subscribers/make_subscribers.html'
    form_class = SubscribersForm
    success_url = '/news/'

    # def get(self, request, *args, **kwargs):
    #     form = self.form_class()
    #     print(form)

    def subscribe_add(self, request):
        categorys = request.POST.getlist('name')
        user = self.user.username
        for category in categorys:
            subscriber = Mailing(categorys=category, subscriber=user)
            subscriber.save()


# class SubscribersForm(ModelForm):
#     def __init__(self, *args, **kwargs):
#         self.authorized_user = kwargs.pop('authorized_user', None)
#         super(SubscribersForm, self).__init__(*args, **kwargs)
        
#         if self.authorized_user:
#             self.fields['subscribers'].initial = self.authorized_user
    
#     class Meta:
#         model = Mailing
#         fields = ['category', 'subscribers']
#         widgets = {
#             'category': forms.Select(attrs={'class': 'form-select'}),
#         }


    # def form_valid(self, form):
    #     subscribe = form.save()
    #     print (subscribe)
        # user = Group.objects.get_or_create(name='common')[0]
        # subscribe.groups.add(user) # добавляем нового пользователя в эту группу
        # subscribe.save()
        # return super().form_valid(form)



    # def get(self, request, *args, **kwargs):
    #     form = self.form_class()
    #     return render(request, self.template_name, {'form': form})

    #В этом коде мы создаем экземпляр формы SubscribersForm с данными из запроса request.POST. Затем мы проверяем, является ли форма валидной. Если форма валидна, мы сохраняем экземпляр модели Subscriber, устанавливаем поле userThrough равным экземпляру пользователя request.user и сохраняем модель.
   
    # def post(self, request, *args, **kwargs):
    #     category_names = request.POST.getlist('category')
    #     for category in category_names:
    #         form = CategorySubscriber(category=category, user=request.user,)
    #         if form.is_valid():
    #             form.save()
    #     return redirect('news:user')

        #Если форма не валидна, мы возвращаем шаблон с формой и ошибками.
        # return render(request, self.template_name, {'form': form})
        

        # form = Subscriber(
	    # userThrough=request.user.username,
        # categoryThrough=request.POST['categoryThrough'],
        # )
        # if form.is_valid():
        #     form.save()
        # return redirect('news:user')
    
     # def get(request):
    #     if request.method == 'POST':
    #         form = SubscribersForm(request.POST)
    #         if form.is_valid():
    #             subscriber = form.save(commit=False)
    #             subscriber.user = request.user
    #             subscriber.save()

    #             # Проверяем наличие email у пользователя
    #             if request.user.email:
    #                 # Отправляем сообщение на email пользователя
    #                 # Ваш код отправки сообщения

    #                 return redirect('news:user')  # Перенаправляем на страницу успешной подписки
    #     else:
    #         form = SubscribersForm()

    #     return render(request, 'subscribe.html', {'form': form})

    # def send_newsletter(category):
    #     subscribers = category.subscribers.filter(id=user.id).exists()
    #     for subscriber in subscribers:
    #         subject = f'{category.subscribers} - Вы подписаны на новостную категорию {category.name}',
    #         message = 'Поздравляю!',
    #         from_email = 'bulanov-rvp@yandex.ru',
    #         # заменить на почту пользователя
    #         recipient_list = ['bylich07@mail.ru'],
    #         html_message = render_to_string('newsletter.html', {'category': category, 'subscriber': subscriber}),
    #         send_mail(subject, message, from_email, recipient_list, html_message=html_message),
    #     return redirect('news:user')




class IndexView(LoginRequiredMixin, TemplateView):
    
    template_name = 'sign/user.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name = 'authors').exists()
        return context
    
@login_required
def upgrade_me(request):
   user = request.user
   author_group = Group.objects.get(name='authors')
   if not request.user.groups.filter(name='authors').exists():
       author_group.user_set.add(user)
   return redirect('news:user')


class RegisterView(CreateView):
   model = User
   form_class = RegisterForm 
   template_name = 'sign/signup.html'
   success_url = '/news/search/'

   def form_valid(self, form):
        user = form.save()
        group = Group.objects.get_or_create(name='common')[0]
        user.groups.add(group) # добавляем нового пользователя в эту группу
        user.save()
        return super().form_valid(form)

class LoginView(FormView):
   model = User
   form_class = LoginForm
   template_name = 'sign/login.html'
   success_url = '/user/'
  
   def form_valid(self, form):
       username = form.cleaned_data.get('username')
       password = form.cleaned_data.get('password')
       user = authenticate(self.request,username=username, password=password)
       if user is not None:
           login(self.request, user)
       return super().form_valid(form)
  
  
class LogoutView(LoginRequiredMixin, TemplateView):
   template_name = 'sign/logout.html'
  
   def get(self, request, *args, **kwargs):
       logout(request)
       return super().get(request, *args, **kwargs)


# @method_decorator(login_required, name='dispatch') 
class PostList(ListView):
    model = Post
    template_name = 'news/news_filter.html' 
    context_object_name = 'posts' 
    queryset = Post.objects.all().order_by('-dataCreation')
    paginate_by = 3

    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['time_now'] = timezone.localtime(timezone.now()) # добавим переменную текущей даты time_now
       context['value1'] = Post.objects.filter(categoryType = 'NW') # добавим ещё одну пустую переменную, чтобы на её примере посмотреть работу другого фильтра
       context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())
       context['choices'] = Post.CATEGORY_CHOICES
       context['form'] = PostForm()
    #    context['choices_category'] = Category.objects.all()
       return context
    
    def post(self, request, *args, **kwargs):
       form = self.form_class(request.POST) 
       if form.is_valid():
           form.save()
       return super().get(request, *args, **kwargs)
    
    # def addpage(request):
    #     form_test = PostTestForm()
    #     return render(request, 'news/news_filter.html', {'form_test':form_test})
    
    

class PostAllView(ListView):
    model = Post
    template_name = 'news/news_all.html' 
    context_object_name = 'posts' 
    queryset = Post.objects.all().order_by('-dataCreation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now()) # добавим переменную текущей даты time_now
        context['value1'] = Post.objects.filter(categoryType = 'NW') # добавим ещё одну пустую переменную, чтобы на её примере посмотреть работу другого фильтра
        context['filter'] = PostFilter(self.request.GET, queryset=self.get_queryset())

        return context

    
class PostDetail(DetailView):
    model = Post
    template_name = 'news/news_one.html' 
    context_object_name = 'post' 

    def get_object(self, *args, **kwargs):
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        if not obj:
            obj = super().get_object(queryset=self.queryset) 
            cache.set(f'post-{self.kwargs["pk"]}', obj)
        return obj
    
    def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       context['time_now'] = timezone.localtime(timezone.now())
       return context

    
class CensoredList(ListView):
    model = Post
    template_name = 'news/news_read.html' 
    context_object_name = 'posts'
    queryset = Post.objects.all().order_by('-dataCreation')

class News(View):
   def get(self, request):
       posts = Post.objects.all().order_by('-dataCreation')
       p = Paginator(posts, 2)

NewsPaper/news/templates/news/news_filter.html
{% extends 'layer/base.html' %}
 
{% block title %}
Новости
{% endblock title %}
 
{% block content %}
<p>время {{ time_now|time:"H:i" }}</p>
<p>текущая дата {{ time_now|date:"d.m.Y" }} г</з>
<p>Найдено количество постов: {{ posts|length }}, из них  новостей: {{ value1|length|default_if_none:"ничего" }}</p>

<h1>НОВОСТИ</h1> 
    <hr>
    {% if posts %} 
    <form method="GET">
        {{ filter.form }}
        <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
        <input class="btn btn-primary" type="submit" value="Найти">
     </form>
     
    <p></p>
     <a href="{% url 'news:post_create' %}"class="btn btn-primary" type="submit">Добавить новость </a>



        <table class="table">
            <tr>
                <th scope="col">
                    Автор
                </th>
                <th scope="col">
                    Категория
                </th>
                <th scope="col">
                    Дата публикации
                </th>
                <th scope="col">
                    Заголовок
                </th>
                <th scope="col">
                    Краткое содержание
                </th>
                <th scope="col">
                    Действия
                </th>
        
            </tr>

        {% for post in filter.qs %} <!-- Для каждого товара будет генерироваться новая строчка, т. е. новый HTML-код. При этом сам цикл работает точно так же, как и в python. product -- переменная цикла, т. е. наш товар, взятый из общего списка -->
            <tr>
                <td>
                    {{ post.author.autorUser }} <!-- Не забываем, что переменные в шаблоне ничем не отличаются от переменных в Python. Здесь также можно получать доступ к полям класса. Например, здесь мы выводим имя, в следующем столбце описание и т.д.  -->
                </td>
                <td>
                    {{ post.get_categoryType_display }}
                </td>
                <td>
                    {{ post.dataCreation|date:'d M Y'  }}
                </td>
                <td>
                    {{ post.titel }}
                </td>
                <td>
                    {{  post.text|truncatewords:20 }}
                </td>
                <td>
                    <a href="{% url 'news:post_update' post.id %}">
                        Update
                    </a>
                    <a href="{% url 'news:post_delete' post.id %}">
                        Delete
                    </a>
                </td>

            </tr>
        {% endfor %}
        </table>
        {% include 'layer/parts/paginator.html' %}

    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

    <!-- <form method="POST">
        {% csrf_token %}
        {{ form }}
        <input class="btn btn-success" type="submit" value="Добавить">
     </form> -->

     <form method='POST'>
        {% csrf_token %}
        <!-- {{ form_test.as_p }}    -->
        {{form_test}} 
    </form>


{% endblock content %}

NewsPaper/news/templates/news/news_one.html
{% extends 'layer/base.html' %}
 
{% block title %}
{{ post.titel|truncatechars:40 }}
{% endblock title %}
 
{% block content %}
<h1>НОВОСТИ</h1> 
<p>время {{ time_now|time:"H:i" }}</p>
{% if post %} 
    <h2>{{ post.titel }}</h3> 
    <i>Дата публикации {{ post.dataCreation|date:'d M Y' }}
        {{ post.dataCreation|time:'H: i' }}

    </i>
    <hr>
    {{ post.text}}


{% else %}
    <h1>'Такой новости нет'</h1> 
{% endif %}

{% endblock content %}

NewsPaper/news/templates/news/news_read.html
{% extends 'layer/base.html' %}
{% load censored_filters %}
 
{% block title %}
Новостной портал, добро пожаловать!
{% endblock title %}
 
{% block content %}
<hr>

{% if posts %} 
    {% for post in posts %} 
    <h2>{{ post.titel|censor }}</h2> 
    <i>Дата публикации {{ post.dataCreation|date:'d M Y'  }}</i>
    <p>{{ post.text|truncatewords:50|censor  }}</p>
    <i>раздел "{{ post.postCategory.name }}", понравилось: {{ post.rating }} человек, автор {{post.author.autorUser.username }}, {{ post.author.ratingAuthor }} ,баллов</i>
    <hr>
    {% endfor %}

{% else %}
    <h1>'Такой новости нет'</h1> 
{% endif %}

{% endblock content %}

NewsPaper/news/templates/news/post_card.html
{% extends 'layer/base.html' %} 
{% block title %} 
  Карточка новости 
{% endblock title %} 

{% block content %}

<h3>Новость добавленна</h3>
<div class="card">
  <div class="card-header">
    <h3>{{ post.titel }}</h3>
    <div>
      Автор: <span class="badge bg-info">{{ post.author.autorUser }}</span> Type:
      <span class="badge bg-info">{{ post.get_categoryType_display }}</span>
    </div>
  </div>
  <div class="card-body">{{ post.dataCreation|date:'d M Y' }}</div>
  <div class="card-body">{{ post.text|truncatewords:20 }}</div>
</div>

<a href="{% url 'news:posts' %}"class="btn btn-primary" type="submit">Далее </a>


{% endblock content %}

NewsPaper/news/templates/news/post_create.html
{% extends 'layer/base.html' %} 
{% block title %} 
  Добавление новости
{% endblock title %} 

{% block content %}

<h3>Post Information</h3>

<form method="POST">
  {% csrf_token %} 
  {{ form }}
  <!-- Теперь нам нужна только готовая форма и кнопка -->
  <input class="btn btn-success my-3" type="submit" value="Добавить" />
</form>

{% endblock content %}

NewsPaper/news/templates/news/post_delete.html
{% extends 'layer/base.html' %} 
{% block title %} 
  Удаление новости 
{% endblock title %} 

{% block content %}

<h3>Delete this post?</h3>
<div class="card">
  <div class="card-header">
    <h3>{{ post.titel }}</h3>
    <div>
      Автор: <span class="badge bg-info">{{ post.author.autorUser }}</span> Type:
      <span class="badge bg-info">{{ post.get_categoryType_display }}</span>
    </div>
  </div>
  <div class="card-body">{{ post.dataCreation|date:'d M Y' }}</div>
  <div class="card-body">{{ post.text|truncatewords:20 }}</div>
</div>


<form method="POST">
  {% csrf_token %}
  <input class="btn btn-danger my-3" type="submit" value="Удалить" />
</form>

{% endblock content %}